In [1]:
# ============================================================
# Imports, Setup, and Data Loading
# ============================================================
import pandas as pd
import numpy as np
import os

# Display settings to see all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

# --- RELATIVE FILE PATHS ---
# 1. Get the current directory 
current_dir = os.getcwd()

# 2. Go up one level to the project root
BASE_DIR = os.path.abspath(os.path.join(current_dir, '..'))

# 3. Define paths to the folders
DATA_DIR = os.path.join(BASE_DIR, 'dataset')
PREPARED_DIR = os.path.join(BASE_DIR, 'prepared_data')

# 4. Create the prepared_data folder if it doesn't exist
os.makedirs(PREPARED_DIR, exist_ok=True)

# 5. Define exact file paths
raw_data_path = os.path.join(DATA_DIR, 'student_career_success_dataset.csv')
clean_data_path = os.path.join(PREPARED_DIR, 'clean_data.csv')

# 6. Load the raw data
df = pd.read_csv(raw_data_path)

print(f"Dataset loaded successfully from: {raw_data_path}")
print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
df.head()

Dataset loaded successfully from: C:\Users\bktsh\OneDrive - Botswana Accountancy College\R&I project and analysis\Student Career Success Prediction new project dataset 2\dataset\student_career_success_dataset.csv
Shape: 50000 rows × 29 columns

,Student_ID,Age,Gender,University_Year,Major,Attendance_Percentage,Study_Hours_Per_Week,CGPA,Academic_Performance,Programming_Skill,Projects_Completed,Certifications,Hackathons,GitHub_Profile,Internships,Leadership_Experience,LinkedIn_Profile,Resume_Score,Communication_Skills,Teamwork,Problem_Solving,English_Proficiency,Interview_Score,Employability_Score,Placement_Status,Company_Tier,Career_Field,Placement_Mode,Starting_Salary_USD
0,ST000001,22,Male,Sophomore,Computer Science,86,21,3.28,Good,9,10,1,6,Yes,5,No,No,100,9,7,8,Advanced,72,231.70,Placed,Tier 1,Backend Developer,Campus Placement,72082
1,ST000002,20,Female,Freshman,Computer Science,64,18,2.53,Poor,6,6,0,5,Yes,2,No,Yes,80,5,6,5,Basic,59,157.45,Not Placed,No Company,Not Placed,Not Applicable,0
2,ST000003,23,Male,Senior,Information Technology,75,19,2.83,Average,8,9,0,5,Yes,3,Yes,No,100,7,8,7,Advanced,76,203.45,Placed,Tier 1,IT Support Engineer,Campus Placement,94898
3,ST000004,23,Female,Senior,Information Technology,80,19,2.80,Average,5,6,3,3,No,2,No,Yes,85,6,6,6,Intermediate,67,171.50,Not Placed,No Company,Not Placed,Not Applicable,0
4,ST000005,23,Female,Senior,Software Engineering,73,19,2.93,Average,9,10,1,2,Yes,3,Yes,Yes,100,10,8,9,Advanced,82,225.45,Placed,Tier 1,Software Engineer,Internship Conversion,85256

In [2]:
# ============================================================
# Check Structure & Missing Values
# ============================================================
print("=" * 60)
print("DATASET INFO")
print("=" * 60)
print(df.info())

print("\nMissing Values per Column:")
print(df.isnull().sum())

============================================================
DATASET INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             50000 non-null  object
 1   Age                    50000 non-null  int64
 2   Gender                 50000 non-null  object
 3   University_Year        50000 non-null  object
 4   Major                  50000 non-null  object
 5   Attendance_Percentage  50000 non-null  int64
 6   Study_Hours_Per_Week   50000 non-null  int64
 7   CGPA                   50000 non-null  float64
 8   Academic_Performance   50000 non-null  object
 9   Programming_Skill      50000 non-null  int64
 10  Projects_Completed     50000 non-null  int64
 11  Certifications         50000 non-null  int64
 12  Hackathons             50000 non-null  int64
 13  GitHub_Profile         50000 non-null  object
 14  Internships            50000 non-null  int64
 15  Leadership_Experience  50000 non-null  object
 16  LinkedIn_Profile       50000 non-null  object
 17  Resume_Score           50000 non-null  int64
 18  Communication_Skills   50000 non-null  int64
 19  Teamwork               50000 non-null  int64
 20  Problem_Solving        50000 non-null  int64
 21  English_Proficiency    50000 non-null  object
 22  Interview_Score        50000 non-null  int64
 23  Employability_Score    50000 non-null  float64
 24  Placement_Status       50000 non-null  object
 25  Company_Tier           50000 non-null  object
 26  Career_Field           50000 non-null  object
 27  Placement_Mode         50000 non-null  object
 28  Starting_Salary_USD    50000 non-null  int64
dtypes: float64(2), int64(14), object(13)
memory usage: 11.1+ MB
None

Missing Values per Column:
Student_ID               0
Age                      0
Gender                   0
University_Year          0
Major                    0
Attendance_Percentage    0
Study_Hours_Per_Week     0
CGPA                     0
Academic_Performance     0
Programming_Skill        0
Projects_Completed       0
Certifications           0
Hackathons               0
GitHub_Profile           0
Internships              0
Leadership_Experience    0
LinkedIn_Profile         0
Resume_Score             0
Communication_Skills     0
Teamwork                 0
Problem_Solving          0
English_Proficiency      0
Interview_Score          0
Employability_Score      0
Placement_Status         0
Company_Tier             0
Career_Field             0
Placement_Mode           0
Starting_Salary_USD      0
dtype: int64

In [3]:
# ============================================================
# Check for Duplicates
# ============================================================
duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicates}")

if duplicates > 0:
    df = df.drop_duplicates()
    print(f"Duplicates removed. New shape: {df.shape}")
else:
    print("No duplicates detected.")

Number of duplicate rows: 0
No duplicates detected.

In [4]:
# ============================================================
# Explore Categorical Variables
# ============================================================
# This helps us identify the target variable and demographic columns
categorical_cols = df.select_dtypes(include=['object']).columns

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().head(10)) # Showing top 10 just in case there are many

--- Student_ID ---
Student_ID
ST000001    1
ST033351    1
ST033329    1
ST033330    1
ST033331    1
ST033332    1
ST033333    1
ST033334    1
ST033335    1
ST033336    1
Name: count, dtype: int64

--- Gender ---
Gender
Male      24533
Female    24465
Other      1002
Name: count, dtype: int64

--- University_Year ---
University_Year
Junior       14870
Senior       12658
Sophomore    12634
Freshman      9838
Name: count, dtype: int64

--- Major ---
Major
Computer Science           12407
Software Engineering        7516
Artificial Intelligence     7505
Data Science                6116
Cybersecurity               4975
Information Technology      4906
Business Analytics          4027
Electrical Engineering      2548
Name: count, dtype: int64

--- Academic_Performance ---
Academic_Performance
Average      28890
Good         18168
Poor          1956
Excellent      986
Name: count, dtype: int64

--- GitHub_Profile ---
GitHub_Profile
Yes    40680
No      9320
Name: count, dtype: int64

--- Leadership_Experience ---
Leadership_Experience
No     30403
Yes    19597
Name: count, dtype: int64

--- LinkedIn_Profile ---
LinkedIn_Profile
Yes    35917
No     14083
Name: count, dtype: int64

--- English_Proficiency ---
English_Proficiency
Advanced        39640
Intermediate     9720
Basic             640
Name: count, dtype: int64

--- Placement_Status ---
Placement_Status
Placed        39040
Not Placed    10960
Name: count, dtype: int64

--- Company_Tier ---
Company_Tier
Tier 1        37152
No Company    10960
Tier 2         1751
Tier 3          137
Name: count, dtype: int64

--- Career_Field ---
Career_Field
Not Placed                   10960
Software Engineer             6544
Data Scientist                3845
AI Engineer                   3792
Backend Developer             3352
DevOps Engineer               3214
Full Stack Developer          3198
Data Analyst                  2749
Machine Learning Engineer     2152
IT Support Engineer           1745
Name: count, dtype: int64

--- Placement_Mode ---
Placement_Mode
Campus Placement         19619
Not Applicable           10960
Off-Campus                7817
Internship Conversion     7674
Referral                  3930
Name: count, dtype: int64

In [5]:
# ============================================================
# Create Binary Target
# ============================================================
TARGET_COL = 'Placement_Status'

# Create the binary column (1 for Placed, 0 for Not Placed)
df['placement_status_binary'] = (df[TARGET_COL] == 'Placed').astype(int)

print(f"Target column created: 'placement_status_binary'")
print(df['placement_status_binary'].value_counts())
print(f"\nPlacement Rate: {df['placement_status_binary'].mean() * 100:.2f}%")

Target column created: 'placement_status_binary'
placement_status_binary
1    39040
0    10960
Name: count, dtype: int64

Placement Rate: 78.08%

In [6]:
# ============================================================
# Save Cleaned Data
# ============================================================
# Save the cleaned dataset using the relative path we defined earlier
df.to_csv(clean_data_path, index=False)

print(f"Cleaned dataset successfully saved to: {clean_data_path}")

Cleaned dataset successfully saved to: C:\Users\bktsh\OneDrive - Botswana Accountancy College\R&I project and analysis\Student Career Success Prediction new project dataset 2\prepared_data\clean_data.csv

In [7]:
# ============================================================
# Preview the Final Data
# ============================================================
# Display the first 20 rows to verify everything is correct before moving to EDA
df.head(20)

,Student_ID,Age,Gender,University_Year,Major,Attendance_Percentage,Study_Hours_Per_Week,CGPA,Academic_Performance,Programming_Skill,Projects_Completed,Certifications,Hackathons,GitHub_Profile,Internships,Leadership_Experience,LinkedIn_Profile,Resume_Score,Communication_Skills,Teamwork,Problem_Solving,English_Proficiency,Interview_Score,Employability_Score,Placement_Status,Company_Tier,Career_Field,Placement_Mode,Starting_Salary_USD,placement_status_binary
0,ST000001,22,Male,Sophomore,Computer Science,86,21,3.28,Good,9,10,1,6,Yes,5,No,No,100,9,7,8,Advanced,72,231.70,Placed,Tier 1,Backend Developer,Campus Placement,72082,1
1,ST000002,20,Female,Freshman,Computer Science,64,18,2.53,Poor,6,6,0,5,Yes,2,No,Yes,80,5,6,5,Basic,59,157.45,Not Placed,No Company,Not Placed,Not Applicable,0,0
2,ST000003,23,Male,Senior,Information Technology,75,19,2.83,Average,8,9,0,5,Yes,3,Yes,No,100,7,8,7,Advanced,76,203.45,Placed,Tier 1,IT Support Engineer,Campus Placement,94898,1
3,ST000004,23,Female,Senior,Information Technology,80,19,2.80,Average,5,6,3,3,No,2,No,Yes,85,6,6,6,Intermediate,67,171.50,Not Placed,No Company,Not Placed,Not Applicable,0,0
4,ST000005,23,Female,Senior,Software Engineering,73,19,2.93,Average,9,10,1,2,Yes,3,Yes,Yes,100,10,8,9,Advanced,82,225.45,Placed,Tier 1,Software Engineer,Internship Conversion,85256,1
5,ST000006,21,Male,Senior,Computer Science,85,32,3.41,Good,9,5,3,4,Yes,3,No,Yes,98,5,6,9,Intermediate,72,210.05,Placed,Tier 1,Software Engineer,Off-Campus,109920,1
6,ST000007,21,Male,Junior,Artificial Intelligence,73,18,3.00,Average,8,8,2,4,Yes,5,No,Yes,100,8,6,6,Advanced,81,219.50,Placed,Tier 1,AI Engineer,Internship Conversion,85010,1
7,ST000008,23,Male,Freshman,Business Analytics,82,20,2.87,Average,4,5,0,1,No,3,No,Yes,86,7,6,4,Intermediate,57,160.35,Not Placed,No Company,Not Placed,Not Applicable,0,0
8,ST000009,23,Female,Freshman,Computer Science,82,39,3.48,Good,8,9,0,5,Yes,5,Yes,No,100,10,10,7,Advanced,100,241.20,Placed,Tier 1,Full Stack Developer,Campus Placement,96175,1
9,ST000010,30,Male,Junior,Information Technology,72,18,2.85,Average,5,3,1,0,No,3,Yes,Yes,78,10,6,5,Advanced,56,166.65,Not Placed,No Company,Not Placed,Not Applicable,0,0
10,ST000011,21,Male,Junior,Data Science,84,31,3.13,Average,7,9,3,1,Yes,3,No,No,100,7,6,8,Intermediate,77,210.95,Placed,Tier 1,Data Scientist,Referral,105190,1
11,ST000012,22,Male,Sophomore,Computer Science,84,16,3.32,Good,8,7,3,2,Yes,5,No,No,100,8,7,9,Advanced,100,239.30,Not Placed,No Company,Not Placed,Not Applicable,0,0
12,ST000013,22,Female,Freshman,Software Engineering,79,16,2.80,Average,7,8,2,3,Yes,4,No,Yes,100,9,6,9,Advanced,76,213.00,Placed,Tier 1,Software Engineer,Internship Conversion,105348,1
13,ST000014,24,Female,Junior,Data Science,71,25,2.94,Average,8,10,1,2,Yes,3,Yes,No,100,10,8,6,Advanced,82,215.60,Not Placed,No Company,Not Placed,Not Applicable,0,0
14,ST000015,20,Male,Junior,Computer Science,73,23,2.98,Average,6,8,2,4,Yes,5,No,No,96,8,7,7,Advanced,100,221.50,Placed,Tier 1,Software Engineer,Off-Campus,78414,1
15,ST000016,25,Male,Junior,Software Engineering,87,29,3.53,Good,10,11,3,3,No,5,No,No,100,9,9,8,Advanced,76,246.45,Placed,Tier 1,DevOps Engineer,Internship Conversion,96148,1
16,ST000017,22,Male,Junior,Computer Science,77,29,3.19,Average,6,6,3,1,Yes,4,No,Yes,96,7,8,7,Intermediate,73,201.65,Placed,Tier 1,Software Engineer,Campus Placement,70471,1
17,ST000018,22,Male,Senior,Cybersecurity,75,27,2.98,Average,7,10,3,1,Yes,4,Yes,Yes,100,9,9,7,Advanced,86,222.20,Placed,Tier 1,Cybersecurity Analyst,Off-Campus,107423,1
18,ST000019,20,Male,Sophomore,Computer Science,100,29,3.42,Good,7,11,1,4,Yes,5,Yes,Yes,100,10,5,7,Advanced,73,228.30,Placed,Tier 1,Software Engineer,Campus Placement,76449,1
19,ST000020,22,Female,Freshman,Computer Science,98,11,3.14,Average,7,11,0,5,Yes,5,Yes,Yes,100,10,9,7,Advanced,80,226.10,Placed,Tier 1,Software Engineer,Internship Conversion,99041,1

In [8]:
# Check placement rate by internship count
print(df.groupby('Internships')['placement_status_binary'].mean().round(4))

Internships
0    0.0678
1    0.2396
2    0.4073
3    0.6190
4    0.8013
5    0.9187
Name: placement_status_binary, dtype: float64

Because students with 0 internships still have a non-zero placement rate (6.7%), this feature cannot be a post-graduation leak. It represents pre-graduation attachments/internships.

The data shows a near-perfect linear relationship: as students complete more internships during their studies, their likelihood of securing a full-time role increases dramatically. Therefore, Internships is retained as the strongest valid pre-placement predictor in the model.

# Notebook 1: Data Preparation — Summary

## Overview
This notebook focused on loading the raw synthetic dataset, assessing its quality, and preparing it for machine learning. The dataset contains 50,000 records and 29 features related to student demographics, academic performance, skills, and placement outcomes.

## Data Quality Checks
- **Missing Values:** None. All 50,000 records are complete.
- **Duplicate Rows:** None detected.
- **Data Types:** The data consists of 14 integer columns, 2 float columns, and 13 categorical (object) columns. 

## Target Variable Creation
The original `Placement_Status` column was categorical ("Placed" / "Not Placed"). To prepare for machine learning models (which require numeric targets), we created a binary target variable:
- `placement_status_binary`: **1** for Placed, **0** for Not Placed.

**Initial Placement Rate:** The clean dataset shows a baseline placement rate of **78.08%** (39,040 placed vs. 10,960 not placed).

## EDA Finding: Validating the "Internships" Feature
A critical step in this notebook was validating whether `Internships` was a post-placement leak or a valid pre-placement predictor. We calculated the placement rate by internship count:
- **0 Internships:** 6.78% placement rate
- **1 Internship:** 23.96%
- **3 Internships:** 61.90%
- **5 Internships:** 91.87%

**Conclusion:** Because students with 0 internships still have a non-zero placement rate (6.7%), this feature cannot be a post-graduation leak (like Starting Salary). It represents **pre-graduation attachments/internships**. The strong linear relationship proves it is the most powerful valid predictor of employability.

## Output
The cleaned dataset (including the new `placement_status_binary` target column) was successfully saved to the `prepared_data` folder as:
- **`clean_data.csv`**

This file will be used in Notebook 2 for Exploratory Data Analysis (EDA) and Notebook 3 for Model Training.